# Generated by Django 3.0.5 on 2020-04-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='title',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
