# Generated by Django 3.0.5 on 2020-04-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0002_reflection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='sharedWith',
            field=models.ManyToManyField(blank=True, null=True, related_name='sharedWith', to='reflections.User'),
        ),
    ]
