# Generated by Django 3.0.5 on 2020-04-17 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='reflections.User'),
        ),
        migrations.AddField(
            model_name='reflection',
            name='sharedWith',
            field=models.ManyToManyField(null=True, related_name='sharedWith', to='reflections.User'),
        ),
    ]
